name: Mac

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      run: brew install boost
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake -DCOMPILE_TESTS=ON ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2
    - name: Test
      working-directory: build
      run: ctest -j2
